---
nodeGroup: "master"
roles:
  master: "true"
  ingest: "false"
  data: "false"
  remote_cluster_client: "false"
  ml: "false"
# extraEnvs:
#   - name: xpack.security.enabled
#     value: "false"
#   - name: xpack.security.transport.ssl.enabled 
#     value: "false"
#   - name: xpack.security.http.ssl.enabled 
#     value: "false"
