---
nodeGroup: "master"
roles:
  master: "true"
  ingest: "false"
  data: "false"
  remote_cluster_client: "false"
  ml: "false"
# extraEnvs:
#   - name: xpack.security.enabled
#     value: "false"
#   - name: xpack.security.transport.ssl.enabled 
#     value: "false"
#   - name: xpack.security.http.ssl.enabled 
#     value: "false"

antiAffinity: "soft"

esJavaOpts: "-Xmx1g -Xms1g"

extraInitContainers:
  - name: file-permissions
    image: busybox
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-master
    securityContext:
      privileged: true
      runAsUser: 0