---
clusterName: elasticsearch
image: gcr.io/planet-4-151612/elasticsearch
imageTag: 7.9.3
# https://www.elastic.co/guide/en/elasticsearch/reference/7.8/cluster-health.html#request-params_wait_for_status
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
