---
nodeGroup: "data"
rbac:
  create: true
replicas: 2
roles:
  data: "true"
  ingest: "true"
  master: "false"
  ml: "false"
  remote_cluster_client: "false"
volumeClaimTemplate:
  storageClassName: ssd
# volumeClaimTemplate:
#   accessModes: [ "ReadWriteOnce" ]
#   storageClassName: "standard"
#   resources:
#     requests:
#       storage: 512M

antiAffinity: "best effort"

extraInitContainers:
  - name: file-permissions
    image: busybox
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-data
    securityContext:
      privileged: true
      runAsUser: 0
